name: ETL Pipeline
run-name: ETL Run
env:
  PYTHON_VERSION: "3.12"

on:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ETL Pipeline
        run: |
          python src/pipeline.py
